version: '3'
services:
  postgres:
    image: postgres:10-alpine
    env_file:
      - './backend/.env'
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - '${POSTGRES_FILE_PATH}:/var/lib/postgresql/data'

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    image: 'api'
    env_file:
      - './backend/.env'
    ports:
      - '${APP_PORT}:3000'
    depends_on:
      - postgres

  front:
    build:
      context: front
      dockerfile: Dockerfile
    env_file:
      - './front/.env'
    image: 'front'
    depends_on:
      - api