version: '3'
services:
  postgres:
    image: postgres:10-alpine
    env_file:
      - './backend/.env.docker'
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - '${POSTGRES_FILE_PATH}:/var/lib/postgresql/data'

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    image: 'api'
    env_file:
      - './backend/.env.docker'
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres

  front:
    build:
      context: front
      dockerfile: Dockerfile
    env_file:
      - './front/.env.docker'
    ports:
      - '${APP_PORT}:${APP_PORT}'
    image: 'front'
    depends_on:
      - api

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    env_file:
      - './.env.docker'
    ports:
      - "8080:80"
    depends_on:
      - api
      - front